#!/bin/bash
cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
	cache=$cachedir/dmenu_run
else
	cache=$HOME/.dmenu_cache # if no xdg dir, fall back to dotfile in ~
fi
cmd=$(
	IFS=:
	if stest -dqr -n "$cache" $PATH; then
		stest -flx $PATH | sort -u | tee "$cache" | dmenu "$@"
	else
		dmenu "$@" < "$cache"
	fi
) 
unset IFS

if [[ $cmd == \!"term "* ]]; then
    x-terminal-emulator -e ${cmd##"\!term "} &
elif [[ $cmd == \!"sudo "* ]]; then
    gksudo ${cmd##\!sudo } &
elif [[ $cmd == \!"where "* ]]; then
    locate ${cmd##\!where } | dmenu "$@" | xargs xdg-open &
elif [[ $cmd == \!"i3 "* ]]; then
    i3-msg ${cmd##\!i3 } &
else
    echo $cmd | ${SHELL:-"/bin/sh"} &
fi
