#!/bin/sh

set -u
set -e

status=$(cat /sys/class/power_supply/BAT0/status)
full=$(cat /sys/class/power_supply/BAT0/energy_full)
now=$(cat /sys/class/power_supply/BAT0/energy_now)
percent=$(echo "100 * ${now} / ${full}" | bc)

printf '%s %2d%%\n' ${status} ${percent}
echo $status

# consider color and urgent flag only on discharge
if [ $status = "Discharging" ]; then
	if [ $percent -lt 20 ]; then
		echo "#FF0000\n"
	elif [ $percent -lt 50 ]; then
		echo "#FFFF00\n"
	else
		echo "#00FF00\n"
	fi
fi
