#!/bin/sh

set -u
set -e

status=$(cat /sys/class/power_supply/BAT0/status)
full=$(cat /sys/class/power_supply/BAT0/energy_full)
now=$(cat /sys/class/power_supply/BAT0/energy_now)
percent=$(python -c "print('%.0f' % ($now / $full * 100))")
full_text="${status} ${percent}%"
short_text=$full_text;

echo $full_text
echo $short_text

# consider color and urgent flag only on discharge
if [ $status = "Discharging" ]; then
	if [ $percent -lt 20 ]; then
		echo "#FF0000\n"
	fi
fi
